Feature branch
Phylis05/rails-forms-project pull request #1
Opened 2020-06-01 17:18 UTC by Phylis05

## Rails-forms-project
#### In this project we:
- Generated User model with username, email, and password
- Generated controllers for the user
- Created the create, edit view templates
- Added validations to the model
- Added error messages

2020-06-01 19:35 UTC, kobiyoyo requested changes
## Hi Team     ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png) 
#### Great Job so far, but there are a few more things required. 
### General
- [x] Check comments below.
### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

2020-06-01 19:35 UTC, kobiyoyo commented on config/routes.rb
> +  resources :users
Let's remove this since you have one below already.

2020-06-01 19:35 UTC, kobiyoyo commented on app/controllers/users_controller.rb
> +    # @user = User.new(username: params[:username], email: params[:email], password: params[:password])
Comments: It’s better to delete commented code.

2020-06-01 19:35 UTC, kobiyoyo commented on app/controllers/users_controller.rb
> +    @user.save
Let's remove this since you have one below already.
`if @user.save` is enough

2020-06-01 19:35 UTC, kobiyoyo commented on app/controllers/users_controller.rb
> +  end
`render :edit` if user was not saved

2020-06-01 19:35 UTC, kobiyoyo commented on app/views/users/new.html.erb
> +# <form accept-charset="UTF-8" action="/users" method="post" >
Lets use this  `<form action=users_path method='post' accept-charset="UTF-8">`

2020-06-01 19:35 UTC, kobiyoyo commented on app/views/users/new.html.erb
> +# <%= form_tag("/users", method: "post") do %>
Lets use this  `<%= form_tag(users_path) do %>`

2020-06-02 09:03 UTC, OdongAlican commented
Thanks @kobiyoyo  for the feedback. We have implemented the recommended changes. Please give us your feedback on the new changes.

2020-06-02 10:52 UTC, suretrust approved these changes
HI team, 👋 

### Great job implementing the suggested changes. 🙌 Let's get this merged! 👍 

_Good luck with your future projects and happy coding!_ 🎉

2020-06-02 16:59 UTC, merged